"""
Per-request state that must never be visible to the model.

The caller's JWT, the correlation id and the idempotency key are set once by the
request handler and read by the tools through these context variables. None of
them is a tool parameter, so the model cannot read one, forge one, or be talked
into substituting someone else's.

Context variables are the right mechanism here and not merely a convenient one:
Strands runs a synchronous @tool through asyncio.to_thread and dispatches
concurrent tools with asyncio.create_task, both of which propagate the current
contextvars.Context. Two requests in flight at once therefore see their own
values. tests/test_context_isolation.py pins that behaviour down.
"""

import contextvars

caller_jwt: contextvars.ContextVar[str | None] = contextvars.ContextVar("caller_jwt", default=None)
correlation_id: contextvars.ContextVar[str | None] = contextvars.ContextVar("correlation_id", default=None)
idempotency_key: contextvars.ContextVar[str | None] = contextvars.ContextVar("idempotency_key", default=None)

# Records every backend call made while serving one request, for the response
# trace and for tests. Set to a fresh list per request.
call_trace: contextvars.ContextVar[list | None] = contextvars.ContextVar("call_trace", default=None)


class MissingCallerIdentity(RuntimeError):
    """Raised when a tool runs outside a request that established a caller."""


def require_jwt() -> str:
    token = caller_jwt.get()
    if not token:
        raise MissingCallerIdentity(
            "No caller JWT in context. Every backend call must carry the end user's own token; "
            "the AI service has no privileged service key for user data."
        )
    return token


def require_idempotency_key() -> str:
    key = idempotency_key.get()
    if not key:
        raise MissingCallerIdentity(
            "No idempotency key in context. It is generated by the request handler, never by the model."
        )
    return key


def record(entry: dict) -> None:
    trace = call_trace.get()
    if trace is not None:
        trace.append(entry)
